# ============================================================
# application.properties - Product Service
# ============================================================

# Server
server.port=8084
spring.application.name=product-service

# MongoDB
spring.data.mongodb.uri=mongodb://mongo_user:mongo_pass@localhost:27017/products_db?authSource=admin
spring.data.mongodb.database=products_db

# Redis Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis_pass
# Tiempo de expiracion del cache en segundos
# 3600 = 1 hora ? despues de 1 hora Redis elimina el producto
# del cache y la proxima busqueda va a MongoDB
spring.cache.redis.time-to-live=3600000
spring.cache.type=redis

# JWT - misma clave secreta que el Auth Service
# El Product Service necesita verificar los tokens que
# genero el Auth Service
jwt.secret=modex-secret-key-super-segura-256-bits-para-hs256-algorithm

# Logging
logging.level.com.modex=DEBUG
logging.level.org.springframework.cache=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus,info
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

# Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false